# -*- encoding: utf-8 -*-
###############################################################################
#                                                                             #
#   purchase_advanced for OpenERP                                             #
#   Copyright (C) 2012 Akretion Sébastien BEAU <sebastien.beau@akretion.com>  #
#                                                                             #
#   This program is free software: you can redistribute it and/or modify      #
#   it under the terms of the GNU Affero General Public License as            #
#   published by the Free Software Foundation, either version 3 of the        #
#   License, or (at your option) any later version.                           #
#                                                                             #
#   This program is distributed in the hope that it will be useful,           #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of            #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
#   GNU Affero General Public License for more details.                       #
#                                                                             #
#   You should have received a copy of the GNU Affero General Public License  #
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.     #
#                                                                             #
###############################################################################



{
    'name': 'purchase_advanced',
    'version': '0.1',
    'category': 'Generic Modules/Others',
    'license': 'AGPL-3',
    'description': """Advanced automatique purchase order management
    All purchase order generated by the scheduler have the state 'draft'
    and the flag 'lock'. A 'lock' purchase order will be updated by
    the scheduler. If you unlock the purchase order and you have new
    procurement, the scheduler will create a new purchase order.
    Also the purchase order are automatically merge per supplier.

    WARNING : you need to apply a patch on your addons.
    Please merge this branch in your addons
    https://code.launchpad.net/~akretion-team/openobject-addons/openobject-addons-purchase-61
    """,
    'author': 'Akretion',
    'website': 'http://www.akretion.com/',
    'depends': ['purchase'], 
    'init_xml': [],
    'update_xml': [ 
           'purchase_view.xml',
    ],
    'demo_xml': [],
    'installable': True,
    'active': False,
}

