# -*- encoding: utf-8 -*-
###############################################################################
#
#   purchase_auto_merge module for OpenERP
#   Copyright (C) 2012-2014 Akretion (http://www.akretion.com)
#   @author: Sébastien BEAU <sebastien.beau@akretion.com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################



{
    'name': 'Purchase Auto Merge',
    'version': '0.1',
    'category': 'Purchase Management',
    'license': 'AGPL-3',
    'summary': 'Automatically group the POs generated by the procurements',
    'description': """
Purchase Auto Merge
===================

With this module, the purchase orders generated by the procurement
scheduler are in *draft* state with the *lock* flag.

When a new procurement is generated:

* if there is already a *lock* purchase order for this supplier, the
procurement scheduler will increase the quantities in this *lock*
purchase order ;

* otherwise, the procurement scheduler will create a new *lock* purchase order.

WARNING : you need to modify your addons to make this module work.
In fact, you need to get the code of this merge proposal :
https://code.launchpad.net/~akretion-team/openobject-addons/trunk-purchase-refactor/+merge/113618
    """,
    'author': 'Akretion',
    'website': 'http://www.akretion.com/',
    'depends': ['purchase'],
    'data': [
        'purchase_view.xml',
    ],
    'installable': True,
    'active': False,
}
